# Cargo.toml
[package]
name = "api-gateway"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "4"
dotenv = "0.15"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
futures = "0.3"

