# Cargo.toml
[package]
name = "auth-service"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "4"
dotenv = "0.15"
serde = { version = "1.0", features = ["derive"] }
jsonwebtoken = "8"
thiserror = "1.0"

