# Cargo.toml
[package]
name = "user-service"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "4"
diesel = { version = "2.0", features = ["postgres", "r2d2"] }
dotenv = "0.15"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

